### ISSUE TITLE
Error in doco

### ISSUE THREAD

**Issue by bsutton** [zim32/mysql.dart#21]
The readme documents how to use the logging version of the package via a get ref.

The example however doesn't work with dart 2.17 as the following format is required:

```
 mysql_client: 
    git: 
      url: https://github.com/zim32/mysql.dart.git
      ref: logging
```
